services:
  postgres-test:
    image: postgres:16
    container_name: postgres-test
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - test-network

volumes:
  pgdata:

networks:
  test-network:
